name: jet_vpn
description: "JET VPN - High Speed Secure VPN"
publish_to: 'none'
version: 1.5.0+15

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_v2ray: ^1.0.10
  http: ^1.2.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5
  percent_indicator: ^4.2.3
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
